version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - ./gradlew build

branches:
  only:
    - main

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

artifacts:
  - path: build/libs/*.war
    name: MyWarFile

